[I 2024-05-08 14:19:02.708 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-05-08 14:19:02.712 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-05-08 14:19:02.716 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-05-08 14:19:02.719 ServerApp] notebook | extension was successfully linked.
[I 2024-05-08 14:19:02.873 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-05-08 14:19:02.902 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-05-08 14:19:02.904 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-05-08 14:19:02.905 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-05-08 14:19:02.906 LabApp] JupyterLab extension loaded from /root/anaconda3/envs/qlib/lib/python3.8/site-packages/jupyterlab
[I 2024-05-08 14:19:02.906 LabApp] JupyterLab application directory is /root/anaconda3/envs/qlib/share/jupyter/lab
[I 2024-05-08 14:19:02.906 LabApp] Extension Manager is 'pypi'.
[I 2024-05-08 14:19:02.933 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-05-08 14:19:02.935 ServerApp] notebook | extension was successfully loaded.
[I 2024-05-08 14:19:02.935 ServerApp] Serving notebooks from local directory: /data/workspace/quantify/qlib/examples
[I 2024-05-08 14:19:02.935 ServerApp] Jupyter Server 2.14.0 is running at:
[I 2024-05-08 14:19:02.935 ServerApp] http://VM-247-46-centos:8081/tree?token=8462fecc4dbb05d4e3cfcdf88d582d9995f1c6e81464a9cc
[I 2024-05-08 14:19:02.935 ServerApp]     http://127.0.0.1:8081/tree?token=8462fecc4dbb05d4e3cfcdf88d582d9995f1c6e81464a9cc
[I 2024-05-08 14:19:02.936 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-05-08 14:19:02.938 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-5284-open.html
    Or copy and paste one of these URLs:
        http://VM-247-46-centos:8081/tree?token=8462fecc4dbb05d4e3cfcdf88d582d9995f1c6e81464a9cc
        http://127.0.0.1:8081/tree?token=8462fecc4dbb05d4e3cfcdf88d582d9995f1c6e81464a9cc
[I 2024-05-08 14:19:02.953 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2024-05-08 14:20:14.946 ServerApp] Creating new notebook in 
[I 2024-05-08 14:20:15.342 ServerApp] Saving file at /Untitled.ipynb
[I 2024-05-08 14:20:15.387 ServerApp] Kernel started: 53e7691e-c95b-4887-a606-b62db984e03c
[I 2024-05-08 14:20:15.745 ServerApp] Connecting to kernel 53e7691e-c95b-4887-a606-b62db984e03c.
[I 2024-05-08 14:20:15.899 ServerApp] Starting buffering for 53e7691e-c95b-4887-a606-b62db984e03c:8de1b42e-ce7e-45ec-8639-69f4d782a395
[I 2024-05-08 14:20:15.903 ServerApp] Connecting to kernel 53e7691e-c95b-4887-a606-b62db984e03c.
[I 2024-05-08 14:20:15.997 ServerApp] Connecting to kernel 53e7691e-c95b-4887-a606-b62db984e03c.
[I 2024-05-08 14:20:16.330 ServerApp] Connecting to kernel 53e7691e-c95b-4887-a606-b62db984e03c.
[I 2024-05-08 14:20:16.761 ServerApp] Connecting to kernel 53e7691e-c95b-4887-a606-b62db984e03c.
[I 2024-05-08 14:20:35.710 ServerApp] Connecting to kernel 53e7691e-c95b-4887-a606-b62db984e03c.
[I 2024-05-08 14:20:38.406 ServerApp] Saving file at /report.py
[W 2024-05-08 14:21:46.430 ServerApp] 404 GET /api/contents/report.ipynb?1715149306313 (9838d1ceb62944468d4b8c87e517e423@10.99.17.88) 0.97ms referer=http://9.134.247.46:8081/notebooks/Untitled.ipynb
[W 2024-05-08 14:21:46.430 ServerApp] 404 GET /api/contents/report.ipynb?1715149306313 (10.99.17.88): No such file or directory: report.ipynb
[I 2024-05-08 14:21:46.475 ServerApp] Uploading file to /report.ipynb
[I 2024-05-08 14:21:47.405 ServerApp] Connecting to kernel 53e7691e-c95b-4887-a606-b62db984e03c.
[I 2024-05-08 14:21:47.782 ServerApp] Kernel started: b6191293-704c-41ae-820d-139ee903a55c
[I 2024-05-08 14:21:48.144 ServerApp] Connecting to kernel b6191293-704c-41ae-820d-139ee903a55c.
[W 2024-05-08 14:23:42.725 ServerApp] 404 GET /hub/api (@9.134.247.46) 11.11ms referer=None
[I 2024-05-08 14:23:49.331 ServerApp] Saving file at /report.ipynb
[I 2024-05-08 14:26:52.258 ServerApp] Starting buffering for 53e7691e-c95b-4887-a606-b62db984e03c:a815eb46-21d5-4e44-8d1f-3ac77e7f0f03
[I 2024-05-08 16:07:51.368 ServerApp] Saving file at /report.ipynb
[I 2024-05-08 18:52:35.394 ServerApp] Starting buffering for b6191293-704c-41ae-820d-139ee903a55c:bc89fa16-6e5f-41ab-83a3-063d70c0d6d0
[I 2024-05-09 05:04:55.480 ServerApp] 302 GET / (@9.135.100.135) 0.42ms
[I 2024-05-09 05:04:56.183 ServerApp] Malformed HTTP message from 9.135.100.135: Malformed HTTP request line
[I 2024-05-09 05:05:12.944 ServerApp] 302 GET / (@9.135.100.135) 0.37ms
[I 2024-05-09 05:05:13.423 JupyterNotebookApp] 302 GET /tree? (@9.135.100.135) 0.65ms
[W 2024-05-09 06:54:05.682 ServerApp] 404 GET http://9.139.82.162/itscan.html (@9.135.100.135) 1.12ms referer=None
[W 2024-05-09 06:54:06.123 ServerApp] 404 GET http://10.99.229.178/itscan.html (@9.135.100.135) 1.07ms referer=None
[W 2024-05-09 06:54:06.848 ServerApp] 404 GET http://9.218.232.52/itscan.html (@9.135.100.135) 1.18ms referer=None
[I 2024-05-09 06:54:08.444 ServerApp] 302 GET / (@9.135.100.135) 0.38ms
[I 2024-05-09 06:54:08.735 JupyterNotebookApp] 302 GET /tree? (@9.135.100.135) 0.42ms
[I 2024-05-09 09:43:27.052 ServerApp] Connecting to kernel 53e7691e-c95b-4887-a606-b62db984e03c.
[W 2024-05-09 09:43:27.353 ServerApp] Notebook report.ipynb is not trusted
[I 2024-05-09 09:43:27.425 ServerApp] Connecting to kernel b6191293-704c-41ae-820d-139ee903a55c.
[I 2024-05-09 09:43:27.504 ServerApp] Starting buffering for 53e7691e-c95b-4887-a606-b62db984e03c:e367fb28-1614-49db-84fb-da3817f92525
[I 2024-05-09 09:43:27.550 ServerApp] Starting buffering for b6191293-704c-41ae-820d-139ee903a55c:57f8b576-6535-4515-a62c-cae4aff814d8
[I 2024-05-09 09:43:29.489 ServerApp] Connecting to kernel b6191293-704c-41ae-820d-139ee903a55c.
[I 2024-05-09 09:43:38.339 ServerApp] Starting buffering for b6191293-704c-41ae-820d-139ee903a55c:e735cb9e-b7db-4c2f-881f-73a95b94603f
[I 2024-05-09 16:59:53.798 ServerApp] Connecting to kernel 53e7691e-c95b-4887-a606-b62db984e03c.
[I 2024-05-09 16:59:53.897 ServerApp] Connecting to kernel b6191293-704c-41ae-820d-139ee903a55c.
[I 2024-05-09 16:59:53.974 ServerApp] Starting buffering for 53e7691e-c95b-4887-a606-b62db984e03c:79558e4d-9fba-4055-a127-ce457ebd0501
[I 2024-05-09 16:59:54.056 ServerApp] Starting buffering for b6191293-704c-41ae-820d-139ee903a55c:100fb6a3-ca72-4dc0-b635-90102a9804f9
[W 2024-05-09 16:59:56.530 ServerApp] Notebook report.ipynb is not trusted
[I 2024-05-09 16:59:57.361 ServerApp] Connecting to kernel 53e7691e-c95b-4887-a606-b62db984e03c.
[I 2024-05-09 16:59:57.483 ServerApp] Connecting to kernel b6191293-704c-41ae-820d-139ee903a55c.
[W 2024-05-09 16:59:57.637 ServerApp] Notebook report.ipynb is not trusted
[I 2024-05-09 16:59:57.809 ServerApp] Starting buffering for 53e7691e-c95b-4887-a606-b62db984e03c:c3ffec00-5af0-4155-8f15-ac850f9b3abc
[I 2024-05-09 16:59:57.819 ServerApp] Starting buffering for b6191293-704c-41ae-820d-139ee903a55c:304c7bae-b45d-4c42-8c4e-ff05ce39c6e6
[I 2024-05-09 16:59:59.859 ServerApp] Connecting to kernel b6191293-704c-41ae-820d-139ee903a55c.
[I 2024-05-09 17:02:00.027 ServerApp] Saving file at /report.ipynb
[I 2024-05-09 17:20:38.386 ServerApp] Starting buffering for b6191293-704c-41ae-820d-139ee903a55c:baca28c3-1e7c-4789-a26e-0cb2cb82caa8
[I 2024-05-10 05:08:08.731 ServerApp] 302 GET / (@9.135.100.135) 0.38ms
[I 2024-05-10 05:08:15.458 ServerApp] Malformed HTTP message from 9.135.100.135: Malformed HTTP request line
[I 2024-05-10 05:08:29.950 ServerApp] 302 GET / (@9.135.100.135) 0.41ms
[W 2024-05-10 06:59:04.947 ServerApp] 404 GET http://9.139.82.162/itscan.html (@9.135.100.135) 0.80ms referer=None
[W 2024-05-10 06:59:05.826 ServerApp] 404 GET http://10.99.229.178/itscan.html (@9.135.100.135) 1.08ms referer=None
[W 2024-05-10 06:59:06.308 ServerApp] 404 GET http://9.218.232.52/itscan.html (@9.135.100.135) 1.07ms referer=None
[W 2024-05-10 08:24:13.782 ServerApp] 404 GET /hub/api (@9.134.247.46) 1.06ms referer=None
[I 2024-05-10 08:24:13.805 ServerApp] 302 GET / (@9.134.247.46) 0.36ms
[I 2024-05-10 08:24:14.207 JupyterNotebookApp] 302 GET /tree? (@9.134.247.46) 0.45ms
[W 2024-05-10 08:24:26.713 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-10 08:24:26.714 ServerApp] 403 GET /api/kernelspecs?1715300666705 (@9.134.247.46) 1.52ms referer=None
[W 2024-05-10 08:24:26.714 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-10 08:24:26.715 ServerApp] 403 GET /api/kernels?1715300666708 (@9.134.247.46) 0.67ms referer=None
[W 2024-05-10 08:24:26.715 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-10 08:24:26.715 ServerApp] 403 GET /api/kernels?1715300666710 (@9.134.247.46) 0.99ms referer=None
[W 2024-05-10 08:24:26.716 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-10 08:24:26.716 ServerApp] 403 GET /api/sessions?1715300666711 (@9.134.247.46) 0.53ms referer=None
[W 2024-05-10 08:24:26.718 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-10 08:24:26.718 ServerApp] 403 GET /api/kernelspecs?1715300666715 (@9.134.247.46) 0.47ms referer=None
[W 2024-05-10 08:24:26.721 ServerApp] 404 GET /hub/api (@9.134.247.46) 0.78ms referer=None
[I 2024-05-10 08:24:26.722 ServerApp] 302 GET / (@9.134.247.46) 0.21ms
[I 2024-05-10 08:24:26.723 JupyterNotebookApp] 302 GET /tree? (@9.134.247.46) 0.31ms
[W 2024-05-10 08:24:27.958 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-10 08:24:27.959 ServerApp] 403 GET /api/kernelspecs?1715300667954 (@9.134.247.46) 0.82ms referer=None
[W 2024-05-10 08:24:27.959 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-10 08:24:27.960 ServerApp] 403 GET /api/kernels?1715300667955 (@9.134.247.46) 0.66ms referer=None
[W 2024-05-10 08:24:27.960 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-10 08:24:27.960 ServerApp] 403 GET /api/kernels?1715300667956 (@9.134.247.46) 0.91ms referer=None
[W 2024-05-10 08:24:27.960 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-10 08:24:27.961 ServerApp] 403 GET /api/sessions?1715300667957 (@9.134.247.46) 0.53ms referer=None
[W 2024-05-10 08:24:27.961 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-10 08:24:27.962 ServerApp] 403 GET /api/kernelspecs?1715300667959 (@9.134.247.46) 0.47ms referer=None
[I 2024-05-10 08:27:14.875 ServerApp] Connecting to kernel 53e7691e-c95b-4887-a606-b62db984e03c.
[I 2024-05-10 08:27:14.973 ServerApp] Connecting to kernel b6191293-704c-41ae-820d-139ee903a55c.
[I 2024-05-10 08:27:15.082 ServerApp] Starting buffering for 53e7691e-c95b-4887-a606-b62db984e03c:7b62b07c-2320-49f0-b485-9a7adc148b44
[I 2024-05-10 08:27:15.157 ServerApp] Starting buffering for b6191293-704c-41ae-820d-139ee903a55c:648e4d9c-745e-4eea-bc79-4f5513ac883a
[I 2024-05-10 08:27:17.866 ServerApp] Connecting to kernel 53e7691e-c95b-4887-a606-b62db984e03c.
[I 2024-05-10 08:27:18.008 ServerApp] Connecting to kernel b6191293-704c-41ae-820d-139ee903a55c.
[I 2024-05-10 08:27:18.205 ServerApp] Starting buffering for 53e7691e-c95b-4887-a606-b62db984e03c:bd1904ec-5147-4b13-8f27-cbd2147f94ff
[I 2024-05-10 08:27:18.286 ServerApp] Starting buffering for b6191293-704c-41ae-820d-139ee903a55c:c14e4619-574e-400f-be92-a5db79ce0a51
[I 2024-05-10 08:27:20.118 ServerApp] Connecting to kernel b6191293-704c-41ae-820d-139ee903a55c.
[I 2024-05-10 08:29:20.958 ServerApp] Saving file at /report.ipynb
[I 2024-05-10 12:11:50.651 ServerApp] Starting buffering for b6191293-704c-41ae-820d-139ee903a55c:2536cdeb-f913-486c-9577-481115e7b158
[I 2024-05-10 16:11:28.898 ServerApp] Connecting to kernel 53e7691e-c95b-4887-a606-b62db984e03c.
[I 2024-05-10 16:11:29.033 ServerApp] Connecting to kernel b6191293-704c-41ae-820d-139ee903a55c.
[I 2024-05-10 16:11:29.298 ServerApp] Starting buffering for 53e7691e-c95b-4887-a606-b62db984e03c:0bf74897-37ae-48cc-baf8-3442a1bcc49f
[I 2024-05-10 16:11:29.389 ServerApp] Starting buffering for b6191293-704c-41ae-820d-139ee903a55c:9fccfc33-922b-4400-a8e1-b07d1b8106e9
[I 2024-05-11 05:06:56.518 ServerApp] 302 GET / (@9.135.100.135) 0.40ms
[I 2024-05-11 05:07:05.389 ServerApp] Malformed HTTP message from 9.135.100.135: Malformed HTTP request line
[W 2024-05-11 05:07:45.360 ServerApp] 405 OPTIONS / (@9.135.100.135) 0.36ms referer=None
[I 2024-05-11 05:07:45.878 ServerApp] Malformed HTTP message from 9.135.100.135: Malformed HTTP version in HTTP Request-Line: 'RTSP/1.0'
[I 2024-05-11 05:07:57.852 ServerApp] 302 GET / (@9.135.100.135) 0.35ms
[I 2024-05-11 05:07:58.527 JupyterNotebookApp] 302 GET /tree? (@9.135.100.135) 0.59ms
[W 2024-05-11 06:54:22.674 ServerApp] 404 GET http://9.139.82.162/itscan.html (@9.135.100.135) 1.03ms referer=None
[W 2024-05-11 06:54:23.366 ServerApp] 404 GET http://10.99.229.178/itscan.html (@9.135.100.135) 1.39ms referer=None
[W 2024-05-11 06:54:23.703 ServerApp] 404 GET http://9.218.232.52/itscan.html (@9.135.100.135) 1.06ms referer=None
[I 2024-05-11 06:54:25.664 ServerApp] 302 GET / (@9.135.100.135) 0.46ms
[I 2024-05-11 06:54:25.919 JupyterNotebookApp] 302 GET /tree? (@9.135.100.135) 0.49ms
[W 2024-05-11 10:48:29.365 ServerApp] 404 GET /hub/api (@9.134.247.46) 1.00ms referer=None
[I 2024-05-11 10:48:29.371 ServerApp] 302 GET / (@9.134.247.46) 0.22ms
[I 2024-05-11 10:48:29.378 JupyterNotebookApp] 302 GET /tree? (@9.134.247.46) 0.27ms
[W 2024-05-11 10:48:35.607 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-11 10:48:35.608 ServerApp] 403 GET /api/kernelspecs?1715395715600 (@9.134.247.46) 0.83ms referer=None
[W 2024-05-11 10:48:35.608 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-11 10:48:35.608 ServerApp] 403 GET /api/kernels?1715395715602 (@9.134.247.46) 0.53ms referer=None
[W 2024-05-11 10:48:35.609 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-11 10:48:35.609 ServerApp] 403 GET /api/kernels?1715395715604 (@9.134.247.46) 0.67ms referer=None
[W 2024-05-11 10:48:35.609 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-11 10:48:35.609 ServerApp] 403 GET /api/sessions?1715395715605 (@9.134.247.46) 0.93ms referer=None
[W 2024-05-11 10:48:35.613 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-11 10:48:35.614 ServerApp] 403 GET /api/kernelspecs?1715395715609 (@9.134.247.46) 0.56ms referer=None
[W 2024-05-11 10:48:35.615 ServerApp] 404 GET /hub/api (@9.134.247.46) 0.76ms referer=None
[I 2024-05-11 10:48:35.616 ServerApp] 302 GET / (@9.134.247.46) 0.21ms
[I 2024-05-11 10:48:35.618 JupyterNotebookApp] 302 GET /tree? (@9.134.247.46) 0.28ms
[W 2024-05-11 10:48:36.182 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-11 10:48:36.182 ServerApp] 403 GET /api/kernelspecs?1715395716177 (@9.134.247.46) 0.81ms referer=None
[W 2024-05-11 10:48:36.183 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-11 10:48:36.183 ServerApp] 403 GET /api/kernels?1715395716178 (@9.134.247.46) 0.62ms referer=None
[W 2024-05-11 10:48:36.183 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-11 10:48:36.183 ServerApp] 403 GET /api/kernels?1715395716179 (@9.134.247.46) 0.89ms referer=None
[W 2024-05-11 10:48:36.184 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-11 10:48:36.184 ServerApp] 403 GET /api/sessions?1715395716180 (@9.134.247.46) 0.52ms referer=None
[W 2024-05-11 10:48:36.185 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/root/anaconda3/envs/qlib/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-11 10:48:36.185 ServerApp] 403 GET /api/kernelspecs?1715395716183 (@9.134.247.46) 0.47ms referer=None
[W 2024-05-11 12:00:33.713 ServerApp] 404 GET /_cluster/health?pretty (@9.135.219.108) 1.05ms referer=None
[W 2024-05-11 12:00:33.757 ServerApp] 404 GET /v1/agent/self (@9.135.219.108) 1.14ms referer=None
[W 2024-05-11 12:00:33.795 ServerApp] 404 GET /version (@9.135.219.108) 0.97ms referer=None
[W 2024-05-11 12:00:33.813 ServerApp] 404 GET http://9.138.206.66/flag.html (@9.135.219.108) 0.66ms referer=None
[W 2024-05-11 12:00:33.830 ServerApp] 404 GET /pods (@9.135.219.108) 0.73ms referer=None
[W 2024-05-11 12:00:33.860 ServerApp] 404 GET /xxl-job-admin/toLogin (@9.135.219.108) 1.06ms referer=None
[I 2024-05-11 12:00:33.905 ServerApp] 302 GET / (@9.135.219.108) 0.32ms
[I 2024-05-11 12:00:33.918 ServerApp] 302 GET /ws/v1/cluster/ (@9.135.219.108) 0.34ms
[W 2024-05-11 12:00:33.923 ServerApp] 404 GET /toLogin (@9.135.219.108) 1.00ms referer=None
[W 2024-05-11 12:00:33.974 ServerApp] 404 GET /v2/keys (@9.135.219.108) 0.75ms referer=None
[I 2024-05-11 12:00:33.992 ServerApp] Malformed HTTP message from 9.135.219.108: Malformed HTTP request line
[I 2024-05-11 12:00:35.001 ServerApp] 302 GET / (@9.135.219.108) 0.45ms
[W 2024-05-11 12:00:35.101 ServerApp] 404 GET /app/kibana (@9.135.219.108) 1.28ms referer=None
[I 2024-05-11 12:00:35.877 ServerApp] 302 GET / (@9.135.219.108) 0.36ms
[I 2024-05-11 15:21:11.041 ServerApp] Connecting to kernel 53e7691e-c95b-4887-a606-b62db984e03c.
[I 2024-05-11 15:21:11.206 ServerApp] Connecting to kernel b6191293-704c-41ae-820d-139ee903a55c.
[I 2024-05-11 15:21:11.403 ServerApp] Starting buffering for 53e7691e-c95b-4887-a606-b62db984e03c:5389f641-2cbe-4b97-a8f3-5a51a9aa8520
[W 2024-05-11 15:21:11.605 ServerApp] Notebook workflow_by_code.ipynb is not trusted
[I 2024-05-11 15:21:11.775 ServerApp] Starting buffering for b6191293-704c-41ae-820d-139ee903a55c:cfc16734-2531-49f9-b15a-608ba2c6d4d0
[I 2024-05-11 15:21:16.822 ServerApp] Kernel started: 4c1bdfa4-142b-431b-b9c7-67b38009bd21
[I 2024-05-11 15:21:17.434 ServerApp] Connecting to kernel 4c1bdfa4-142b-431b-b9c7-67b38009bd21.
[I 2024-05-11 15:21:20.514 ServerApp] Starting buffering for 4c1bdfa4-142b-431b-b9c7-67b38009bd21:04d91574-db83-4ab1-87fd-146e1fa774ec
